[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
morph_holesky = "https://rpc-quicknode-holesky.morphl2.io"
morph_mainnet = "https://rpc-quicknode.morphl2.io"

[etherscan]
morph_holesky = { key = "${API_KEY_BLOCKSCOUT}", url = "https://explorer-api-holesky.morphl2.io/api" }
morph_mainnet = { key = "${API_KEY_BLOCKSCOUT}", url = "https://explorer-api.morphl2.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config 